# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Site settings
title: Coding Profile
description: >- # this means to ignore newlines until "baseurl:"
github_username:  your_github_username   
